### ISSUE TITLE
Graphing

### ISSUE THREAD

**Issue by CasperSpronk** [MichielOHerne/BigData5#12]
de data komt binnen als json bestand. Hier wordt over gefilterd en worden de tweets gesorteerd op hashtag en wordt er een sentiment analysis over gedaan. De sentiment analysis moet worden geplot in een grafiek met op de y-as de sentiment (positief/negatief) en op de x-as de tijd. de titel van de grafiek moet de hashtag zijn
 

voorbeeld van gesorteerde tweet
["#ditiseentweet", ["hier staat een tweet #ditiseentweet", [compound, negative, neutral, positive], timestamp], ["nog een tweet #ditiseentweet , [compound, negative, neutral, positive], timestamp], ....]

**Comment by TimAl** [comment]
Gefikst, zie branch Result-Plot.
Verbeteringen volgen, basisfunctionaliteit werkt (dus je kan het al gebruiken).
